version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gql-gateway:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: nest-gql
        PORT: 3000
    environment:
      USER_SERVICE_URL: users:50051
    ports:
      - "3000:3000"
    command: [ "pnpm", "start" ]

  users:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: users
        PORT: 50051
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_NAME: test
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "pnpm", "start", "users" ]

volumes:
  postgres-data:
